- Python/README.md
- Python/shortest_path_unweighted.py
Yes
Shortest path in unweighted graph using Breadth First Search
#4
> Shortest path in Unweighted Graph (using BFS)

- Python/README.md
- Python/shortest_path_unweighted.py
- Python/ufds.py
Yes
Union-Find Data Structure for set operations
#6
> Union-Find Data Structure in Python

- JavaScript/README.md
- JavaScript/binary_search.js
Yes
A JavaScript function that receives 2 values, an array and a key value assuming this array is sorted, we start doing the binary search algorithm starting in the middle, if the middle value is exactly the key number we return its position (middle) if the key is higher we reassign start to middle + 1, basically incrementing our middle position (the position we are trying to center the value on).
Fixes Issue
#2
> Implemented JavaScript binary search

- CPP/README.md
- CPP/Row with minimum number of 1s in C++.cpp
Yes
Using STL and vectors to solve the problem
- [ Yes] I've read the contribution guidelines.
- [ Yes] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the README.md and link to my code.
Fixes Issue : https://github.com/manan025/DS-Algo-Zone/issues/9
<br/>
> Row with minimum number of 1

- Java/README.md
- Java/min_number_of_1.java
YES
The java program find the row with minimum number of 1s and print them.
- [Y ] I've read the contribution guidelines.
- [ Y] I've checked the issue list before deciding what to submit.
- [ Y] I've edited the README.md and link to my code.
#9 
Fixes Issue : YES
<br/>
> Min number of 1s in java

- Python/README.md
- Python/lengthOfLongestSubstring.py
yes
problem solved
- [ Y] I've checked the issue list before deciding what to submit.
- [ Y] I've edited the README.md and link to my code.
Fixes Issue #13 
yes
> Length of Longest Substring added

- Kotlin/README.md
- Kotlin/binary_Search.kt
Yes
i have written the code of binary search using Kotlin language.
Fixes Issue
<br/>
i have fixed the issue according to the given constrain.
> binary search code using kotlin

- Java/PalindromeString.java
- Java/README.md
Yes
JAVA code to check if entered String is palindrome or not (ie. Palindrome String remains the same when reversed)
Fixes Issue #14 
<br/>
> Added PalindromeString.java to check if entered String is palindrome

- CPP/Longest_Substring_without_repeating_characters.cpp
Added longest substring without repeating characters problem
(Yes, I have followed them.)
(I have added the solution of Longest substring without repeating characters in C++)
Fixes Issue
<br/>
> Added Longest substring problem

- CPP/README.md
Added Longest Substring without Repeating characters
Fixes Issue
<br/>
> Added Longest substring problem --Issue #13

- CPP/README.md
- CPP/linear_search.cpp
Yes
Added code for linear search in C++
- [ ✔️] I've read the contribution guidelines.
- [ ✔️] I've checked the issue list before deciding what to submit.
- [✔️ ] I've edited the README.md and link to my code.
Fixes Issue
<br/>
Adds Linear Search in C++
> Added Linear Search in CPP

- JavaScript/Check_Palindrome.js
- JavaScript/README.md
Yes
Javascript code for Palindrome check
Fixes Issue #14
<br/>
> Added Palindrome Check Javascript Issue #14

- C/README.md
- C/binary_search.c
Yes
Added binary search implementation in C along with its complexity analysis to the C folder and updated the respective README.
Fixes Issue #2
- Added binary search program with complexity analysis
- Updated README
> Added binary search implementation in C and Updated README

- JavaScript/README.md
- JavaScript/linear_search.js
Yes
Linear Search in an Array in JavaScript
Fixes Issue #28 
<br/>
> Added Linear Search in JavaScript

- CPP/README.md
- CPP/insertion_sort.cpp
Yes
Added code for insertion sort in C++
- [ ✔️] I've read the contribution guidelines.
- [ ✔️] I've checked the issue list before deciding what to submit.
- [ ✔️] I've edited the README.md and link to my code.
Fixes Issue
<br/>
Adds code for insertion sort in C++
> Added Insertion Sort in CPP

- C/stack.c
Yes
Stack in C. 
Issue no. #24
> Added stack in C. Updated Readme.md

- C/README.md
- C/linear_search.c
Yes
Added linear search implementation in C along with its complexity analysis to the C folder and updated the respective README.
Fixes Issue #28 
- Added linear search program with complexity analysis
- Updated README
> Added linear search implementation in C and updated README

- CPP/README.md
- CPP/Union_find.cpp
(Yes)
(Union-Find DS implemented in C++)
Fixes Issue #6 
<br/>
> Union-Find Ds added

- Java/Longest_Substring_Without_Repeating_Characters.java
- Java/README.md
Yes 
Added solution for Longest Substring Without Repeating Characters in java
- [ ✔️] I've read the contribution guidelines.
- [ ✔️] I've checked the issue list before deciding what to submit.
- [ ✔️] I've edited the README.md and link to my code.
Fixes Issue
<br/>
Adds code for  Longest Substring Without Repeating Characters in java
> Added Longest Substring Without Repeating Characters in java

- Java/LinearSearch.java
- Java/README.md
Yes
Add linear search in java
[ ✔️] I've read the contribution guidelines.
[ ✔️] I've checked the issue list before deciding what to submit.
[ ✔️] I've edited the README.md and link to my code.
Fixes Issue
<br/>
#28
> Add linear search in java

- JavaScript/README.md
- JavaScript/min_number_of_1.js
Yes
Implemented solution of problem Min number rows with 1 using javascript
Fixes Issue #9 
<br/>
> Min number rows with 1 using javascript

- Python/LinearSearch.py
- Python/README.md
Yes
Python solution for LinearSearch(Issue #28) 
Fixes Issue
<br/>
#28
> Added LinearSearch Python code

- JavaScript/README.md
- JavaScript/insertion_sort.js
Yes
Added insertion sort code in Javascript
- [ ✔️] I've read the contribution guidelines.
- [ ✔️] I've checked the issue list before deciding what to submit.
- [ ✔️] I've edited the README.md and link to my code.
Fixes Issue
<br/>
Adds Insertion sort in JavaScript
> Added Insertion Sort in JS

- Python/sorting.py
> added sorting.py

- Java/README.md
- Java/SelectionSort.java
Yes
Added files for selection sort in java
[ ✔️] I've read the contribution guidelines.
[ ✔️] I've checked the issue list before deciding what to submit.
[ ✔️] I've edited the README.md and link to my code.
Fixes Issue
<br/>
#51
> Added Selection Sort in Java

- Python/quicksort.py
> added quicksort.py

- C/README.md
- C/insertion_sort.c
Yes
Added Insertion Sort using C and Updated Readme.md 
Fixes Issue
<br/>
#34 
> Added Insertion Sort using C and Updated Readme.md

- Python/README.md
- Python/binarySearch.py
Yes
binary search program in python
Fixes Issue #2 Python
<br/>
> Binarysearch py

- Python/README.md
- Python/bubbleSort.py
Yes
Bubble sort in python
Fixes Issue #1 
<br/>
> bubblesort.py

- Python/README.md
- Python/selectionSort.py
Yes
Selectin Sort in python
- [y] I've read the contribution guidelines.
Fixes Issue
yes
> Selection Sort added

- JavaScript/README.md
- JavaScript/selection_sort.js
Yes
Added JavaScript code to implement Selection Sort
Fixes Issue #51 
<br/>
> Added JavaScript Code for Selection Sort

- JavaScript/README.md
- JavaScript/bubble_sort.js
Yes
Added code for bubble sort implemented in JavaScript
Fixes Issue #1 
<br/>
> Added Bubble Sort in JavaScript

- Python/MergeSort.py
- Python/README.md
Yes
Added the Merge sort using python language
Issue #60
> Merge sort python (Issue #60)

- Java/QuickSort.java
- Java/README.md
Yes
Implemented Quick Sort in Java
**Fixed Issue #62**
> Added Quick Sort program in Java

- Java/README.md
- Java/bubbleSort.java
Yes
Bubble Sort program in java is added.
Fixes Issue #1 
<br/>
> Bubble Sort program in java

- Python/countinversion.py
> count inversion algorithm

- CPP/Kadane's_Algorithm.cpp
- CPP/README.md
Yes
This is code is tried and tested on Leetcode
> add Kadane's_Algorithm in cpp

- Python/random_select.py
>  random_select algo

- Kotlin/README.md
- Kotlin/palindrome.kt
Yes
Adds kotlin algorithm for checking a palindrome.
Contributes kotlin solution to Issue #14.
> add kotlin palindrome checker and update kotlin readme

- CPP/Max_Sum_Inc_Subs.cpp
- CPP/README.md
YES
Write a program to find the sum of the maximum sum subsequence of the given array such that the integers in the subsequence are sorted in increasing order.
Fixes Issue
<br/>
#87
> Max Sum Inc Subsequence

- CPP/README.md
> Issue #24 Updated README.md

- CPP/Djikstra's_Algorithm.cpp
- CPP/README.md
Yes
Add Dijkstra Algorithm to find single source shortest path in weighted graph.
Fixes Issue
<br/>
#78
> Dijkstra Algorithm in C++

- C/README.md
- C/merge_sort.c
Yes
Add merge sort algorithm using c
Fixes Issue #60
> Add merge sort using c (Issue #60)

- Java/FloydAlgorithm.java
- Java/InsertionSort.java
- Java/README.md
Yes
- [yes ] I've read the contribution guidelines.
- [ yes] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the README.md and link to my code.
Fixes Issue
<br/>
Found an issue in insertion sort. Fixed it.
> Floyd Algorithm and Insertion sort bug fix

- C/README.md
- C/bubbleSort.c
yes
Bubble Sort program in C
Fixes Issue
Yes
> Bubble Sort added

- Java/README.md
- Java/TowerOfHanoi.java
- Java/TowerOfHanoiRecursive.java
Yes, I have.
Added a solution for the Tower of Hanoi problem in Java.
Fixes Issue #113  
<br/>
> Tower of Hanoi recursive solution in Java

- Kotlin/README.md
- Kotlin/min_number_of_1.kt
Yes
Kotlin program to find the rows with minimum number of 1s and print them.
- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the README.md and link to my code.
Fixes Issue : [#9](https://github.com/manan025/DS-Algo-Zone/issues/9)
> Rows with minimum number of 1s in Kotlin

- Python/MaximumSumIncreasingSubsequence.py
- Python/README.md
Yes
Maximum Sum Increasing Subsequence in Python
Fixes Issue
<br/>
#87
> Maximum Sum Increasing Subsequence in Python

- C/Quick_Sort.c
- C/README.md
That's my first time to work on github and open source  if there is anything wrong please let me know so that i can improve myself .
> Added Quick short in c and update Readme file

- Python/Floyd.py
- Python/README.md
yes
Floyd in python
Fixes Issue
<br/>
#81
> Floyd in python

- Java/BreadthFirstSearch.java
- Java/README.md
Yes
- Shortest Path in unweighted graph using BFS (in Java) program added.
- Relevant  input, output, comments, complexity provided
Fixes Issue
<br/>
Issue #4
> Shortest Path using BFS (in Java) added

- Python/README.md
- Python/kadanes_algorithm_largest_sum_contiguous_subarray.py
Yes
Added Kadane's Algorithm to find largest sum contiguous subarray in Python and updated Readme.md
Fixes Issue
<br/>
#68
> Added Kadane's Algorithm in Python and Updated Readme.md

- Go/README.md
- Go/mergesort.go
Yes
- Added Merge Sort in GOLang
Fixes Issue #60 
<br/>
> added mergesort in GO

- CPP/BFS.cpp
- CPP/DFS.cpp
- CPP/README.md
YES
- Added DFS and BFS traversal in an Undirected Graph
Fixed Issue #120 
<br/>
> added codes of DFS and BFS

- Python/README.md
- Python/towerOfHanoi.py
Yes
Tower of hanoi recurive in python
Fixes Issue #113  Python recursive
<br/>
> towerOfHanoi.py recusive

- CPP/README.md
- CPP/quick_sort.cpp
Yes
Implemented Quick Sort in Cpp
Fixed Issue #62
> quick sort cpp

- JavaScript/README.md
- JavaScript/tower_of_hanoi_recursive.js
Yes
I have added Tower of Hanoi - Recursive - JavaScript
#113 
Fixes Issue
<br/>
> Tower of Hanoi Recursive JavaScript Added

- Java/FloydAlgorithm.java
Yes
Complete code for Floyd algorithm in java.
Fixes Issue
<br/>
> Floyds Algorithm for removal of loop

- C/README.md
- C/Tree_Traversals.c
YES
Added PreOrder, PostOrder and InOrder Traversal in Binary Tree
Fixes Issue #132 
<br/>
> Added PreOrder, PostOrder and InOrder Traversal in Binary Tree

- CPP/README.md
- CPP/binary_tree_recursive_traversals.cpp
Yes
Recursive Traversals of Binary Tree
Fixes Issue
<br/> #132
> Binary Tree Recursive Traversal #132

- Java/Euclid_algorithm.java
- Java/README.md
Yes, I read that.
Describe how to find gcd from worst way to best way.
- [ Done] I've read the contribution guidelines.
- [Done ] I've checked the issue list before deciding what to submit.
- [Done ] I've edited the README.md and link to my code.
issue number -  #158
Fixes Issue
<br/>
Thank you.
> euclid_algo (GCD) in java language.

- CPP/README.md
- CPP/equal_partition_subset_sum.cpp
YES
Code for the equal partition subset sum problem
Fixes Issue #159 
<br/>
> Equal partition subset sum

- CPP/Level_order_traversal_BST.cpp
- CPP/README.md
Yes
Added Level order traversal in BST
Fixes Issue #151 
<br/>
> Added Level order traversal in BST

- CPP/README.md
- CPP/gold_mine_using_dp.cpp
Yes
Added Solution for Gold Mine using DP in C++ and updated Readme.md
Fixes Issue
<br/>
#154 
> Added Gold mine using DP in C++ and Updated Readme.md

- Kotlin/QuickSort.kt
- Kotlin/README.md
Yes
Quicksort implemented in Kotlin.
- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the README.md and link to my code.
Fixes Issue : [#62](https://github.com/manan025/DS-Algo-Zone/issues/62)
> Added Kotlin implementation for Quicksort

- Java/Goldmine.java
- Java/README.md
Yes
Written the code for gold mine problem in Java
Fixes Issue #154 
<br/>
> Gold mine problem in java and updated README.md

- CPP/README.md
- CPP/Segment_tree.cpp
YES
Added Segment Tree code
Fixes Issue  #173 
<br/>
> Added segment tree code

- Go/README.md
- Go/binarySearch.go
Yes
Binary Search program in go
Fixes Issue
Yes
> Binary Search added

- CPP/Morris_Preorder_and_Inorder_Traversal.cpp
- CPP/README.md
- CPP/Vertical_Traversal_of_Binary_tree.cpp
Yes
Morris Preorder and Inorder Traversal for Binary Trees uses O(1) space and no recursion.
Code is Tested
Fixes Issue
<br/> Morris Traversal of Binary Trees O(1) Space ( Inorder , Preorder ) #133
> Morris Traversal

- CPP/README.md
- CPP/Vertical_Traversal_of_Binary_tree.cpp
Yes
Tested C++ code for vertical order traversal of binary tree
Fixes Issue
<br/>#108
> Vertical Traversal of binary tree

- Python/Insertion_Sort.py
- Python/README.md
Yes
Insertion Sort added in Python language
Fixes Issue
<br/>
#34
> Insertion sort added in python

- C/README.md
- C/fibonacci_series_code.c
Yes
Yes
Fixes Issue
<br/>
#130
> Added code for Fibonacci series in C

- .idea/.name
- .idea/runConfigurations.xml
- Java/InsertionInLinkedList.java
Yes I have.
I have added the Program of Insertion in Linked List #196.
#196
> (ISSUE RESOLVE) Added a Program of Insertion in Linked List

- toposort in C#
Yes
Topological sort in C#
Issue No #177 
Fixes Issue
<br/>
> toposort in C#

- C/TopologicalSorting.c
Yes
Topological Sorting in C
Fixes Issue
<br/>
#177
> Topological Sorting in C

- Kotlin/README.md
- Kotlin/Stack.kt
Yes
Kotlin Implementation of Stacks
Fixes Issue [#24](https://github.com/manan025/DS-Algo-Zone/issues/24)
> Added Kotlin Implementation of Stacks

- CPP/README.md
- CPP/Topological_sorting.cpp
YES
Added code for topological sorting and analyzed its time complexity.
Fixes Issue #177 
<br/>
> Added Topological_sorting
